# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    cocoapods
  end

  desc "Increase build_number and version_number"
  lane :increase_build_number do
    increment_build_number(xcodeproj: 'Tastie.xcodeproj')
    version = prompt(text: "How to versioning this release? 'major', 'minor', 'patch(default)'")
    case version
    when 'major'
      increment_version_number(bump_type: "major")
    when 'minor'
      increment_version_number(bump_type: "minor")
    else
      increment_version_number(bump_type: "patch")
    end
    commit_version_bump(xcodeproj: 'Tastie.xcodeproj', force: true)
    push_to_git_remote(remote_branch: "beta", force: true)
  end

  desc "Push a new release beta build to the App Store"
  lane :beta do
    sync_code_signing(type: "appstore", readonly: true, app_identifier: "me.tastie.client")
    build_app(scheme: "Tastie", output_directory: './fastlane/build')
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    sync_code_signing(type: "appstore", readonly: true, app_identifier: "me.tastie.client")
    build_app(scheme: "Tastie", output_directory: './fastlane/build')
    upload_to_app_store
  end
end
